### ISSUE TITLE
CRC support

### ISSUE THREAD

**Issue by pronebird** [leetal/AWFileHash#3]
Is it possible to add support for CRC?

**Comment by leetal** [comment]
I'll look into this when i have time in the coming week or so. Loots to do at work right now :/

**Comment by pronebird** [comment]
Same here. I'll send you PR if I get to that faster.

**Comment by leetal** [comment]
Almost a year later. CRC32b implemented.

**Comment by pronebird** [comment]
@leetal kudos!
